### ISSUE TITLE
module.exports instead of global polyfill?

### ISSUE THREAD

**Issue by dfcreative** [YuzuJS/setImmediate#48] opened 2015-08-27 01:12 UTC
Hi!
I've tried to use this module by the CommonJS convention, like that:
```js
var setImmediate = require('setimmediate');
setImmediate(function () {});
```
And found out that this code doesn't work.

Is there a specific reason you keep to exposing `setImmediate` to the global scope instead of exporting a module?

It's quite uncomfortable to use that as a polyfill as a module, because there's a special service for polyfills, [polyfill.io](https://cdn.polyfill.io/v1/docs/features/#setImmediate), which ensures the environment and in that a user can avoid importing polyfills as dependencies.

Besides, user can always compile module standalone with `browserify -s`, so it is not necessary to force him into using global-scope setImmediate.

**Comment by domenic** [comment] 2015-08-27 01:14
Dupe of #16.

**Closed by domenic** 2015-08-27 01:14 UTC

**Comment by dfcreative** [comment] 2015-08-27 01:25
Well, it's actually a case when I use ES6 modules instead of commonJS:

```js
import setImmediate from 'setimmediate'
```

I don't want to know commonJS format anymore, but babel forces compilation of ES6 modules into commonJS (by default). How I'm supposed to deal with it then?

**Comment by domenic** [comment] 2015-08-27 01:26
`import 'setimmediate'`

**Comment by dfcreative** [comment] 2015-08-27 01:26
Right

**Comment by episodeyang** [comment] 2016-04-01 23:07
this is fantastic. We should add this to readme. 

For the record, I'm using typescript and this works flawlessly.
