### ISSUE TITLE
bower

### ISSUE THREAD

**Issue by wheresrhys** [YuzuJS/setImmediate#45] opened 2015-06-22 10:28 UTC
Would be great to have this little util in the bower registry

**Comment by herby** [comment] 2015-06-22 11:36
Tags are proper semver, so in the meantime you can `bower install setimmediate=git://github.com/YuzuJS/setImmediate.git --save`.

**Comment by domenic** [comment] 2015-06-22 14:32
Dupe of #19, #43.

**Closed by domenic** 2015-06-22 14:32 UTC
